name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: nobodyxu/rust-and-clang
    steps:
      - name: List version of the software
        run: |
          set -xe
          cargo --version
          clang --version
          ld.lld --version
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Listing the dir for debugging
        run: tree
      - name: Build
        run: RUSTFLAGS="-C link-args=-fuse-ld=lld -Z sanitizer=address" cargo +nightly build -v
      - name: Run tests
        run: RUSTFLAGS="-C link-args=-fuse-ld=lld -Z sanitizer=address" cargo +nightly test -v -- --nocapture
