name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependency
      run: sudo apt update && sudo apt install -y lld
    - name: Listing the dir for debugging
      run: tree
    - name: Build
      run: sh -c "cargo build -vv; ls -lsh aspawn/"
    - name: Run tests
      run: cargo test --verbose
