name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -A dead_code

jobs:
  build:
    runs-on: ubuntu-latest
    container: nobodyxu/rust-and-clang
    steps:
      - name: List version of the software
        run: |
          set -xe
          cargo --version
          clang --version
          ld.lld --version
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Listing the dir for debugging
        run: tree
      - name: Build
        run: cargo build -v
      - name: Run tests
        run: cargo test -v
